config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:create, :new, :show, :destroy]
  resource :session, only: [:create, :new, :destroy]
  resources :subs
  resources :posts

end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  sub_id     :integer          not null
#  author_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ActiveRecord::Base
  belongs_to :author,
    class_name: :User
  belongs_to :sub
  validates :title, :sub_id, :author_id
end

app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :integer          not null, primary key
#  title        :string           not null
#  description  :string           not null
#  moderator_id :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Sub < ActiveRecord::Base
  belongs_to :moderator,
    class_name: :User
  has_many :subs
  validates :title, :description, :moderator_id, presence: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  attr_reader :password
  validates :username, :email, presence: true, uniqueness: true
  validates :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 2, allow_nil: true, message: "must be at least 6 characters" }
  before_validation :ensure_session_token
  has_many :subs
  has_many :posts

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(password_digest).is_password?(password)
  end

  def generate_session_token
    SecureRandom.urlsafe_base64(16)
  end

  def reset_session_token!
    self.session_token = generate_session_token
    self.save!
    self.session_token
  end

  private
  def ensure_session_token
    self.session_token ||= generate_session_token
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
  #TODO -authenticity token
  helper_method :logged_in?, :current_user
  def current_user
    User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_in(user)
    user.reset_session_token!
    session[:session_token] = user.session_token
  end

  def log_out!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def require_signed_in!
    flash[:errors] = ["must sign in"]
    redirect_to new_session_url unless logged_in?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def create
  end

  def new
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by_credentials(params[:username], params[:password])
    if user
      log_in(user)
      redirect_to user_url(user)
    else
      flash.now[:errors] = user.errors.full_messages
      render :new
    end
  end

  def new
    render :new
  end

  def destroy
    log_out!
    redirect_to new_session_url
  end
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_signed_in!, except: [:index, :show]
  before_action :require_user_own_sub, only: [:edit, :update]

  def create
    redirect_to new_session_url unless logged_in?
    @sub = Sub.new(title: sub_params[:title], description: sub_params[:description], moderator_id: current_user.id)
    if @sub.save
      render :show
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def new
    render :new
  end

  def index
  end

  def show
    render :show
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private
  def sub_params
    params.require(:sub).permit(:title, :description)
  end

  def require_user_own_sub
    sub = Sub.find_by(id: params[:sub][:id])
    unless sub.moderator_id == current_user.id
      redirect_to new_session_url unless logged_in?
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      redirect_to user_url(@user)
    else
      # render text: user.errors.full_messages
      flash[:errors] = @user.errors.full_messages
      redirect_to new_user_url
    end
  end

  def new
    render :new
  end

  def show
    @user = User.find_by(id: params[:id])
    render :show
  end

  def destroy
    log_out!(current_user)
    redirect_to new_user_url(current_user)
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reddit</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<img src="/owl.jpg" alt="awesome">
<%= yield %>
<% if logged_in? %>
<%= link_to "Sign out", session_url, method: :delete %>
<% else %>
<%= link_to "Sign in", new_session_url, method: :get %>
<%= link_to "Sign up", new_user_url, method: :get %>
<% end %>
</body>
</html>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

app/views/posts/new.html.erb
<h1>Posts#new</h1>
<p>Find me in app/views/posts/new.html.erb</p>

app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

app/views/subs/create.html.erb
<h1>Subs#create</h1>
<p>Find me in app/views/subs/create.html.erb</p>

app/views/subs/destroy.html.erb
<h1>Subs#destroy</h1>
<p>Find me in app/views/subs/destroy.html.erb</p>

app/views/subs/edit.html.erb
<h1>Subs#edit</h1>
<p>Find me in app/views/subs/edit.html.erb</p>

app/views/subs/index.html.erb
<h1>Subs#index</h1>
<p>Find me in app/views/subs/index.html.erb</p>

app/views/subs/new.html.erb
<h1>Create a Subreddit</h1>

<form action="<%= subs_url %>" method="post">
  <label>Title</label>
  <input type="string" name="sub[title]" value="">
  <br>
  <label>Description</label>
  <input type="text" name="sub[description]" value="">
  <br>
  <input type="submit" value="Create subreddit">
</form>

app/views/subs/show.html.erb
<h1>Subs#show</h1>
<p>Find me in app/views/subs/show.html.erb</p>

app/views/subs/update.html.erb
<h1>Subs#update</h1>
<p>Find me in app/views/subs/update.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up!</h1>

<form action="<%= users_url %>" method="post">
  <label>Username</label>
  <input type="string" name="user[username]" value="">
  <br>
  <label>Email</label>
  <input type="string" name="user[email]" value="">
  <br>
  <label>Password</label>
  <input type="password" name="user[password]" value="">
  <br>
  <input type="submit" value="Register">
</form>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>